[project]
name = "figureforge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "maxawake", email = "max.m.richter@protonmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "appdirs>=1.4.4",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pyside6>=6.11.2",
    "requests>=2.34.2",
]

[project.scripts]
figureforge = "figureforge:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
