"""Artist inspection, transactional edits, and executable code export."""

import base64
import copy
import io
import json
import math

import numpy as np
from matplotlib.artist import ArtistInspector
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.figure import Figure


DEMO_SOURCE = '''import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(8, 5), layout="constrained")
x = np.linspace(0, 2 * np.pi, 120)
ax.plot(x, np.sin(x), color="#6366f1", linewidth=2.5, label="Sine")
ax.plot(x, np.cos(x), color="#14b8a6", linewidth=2.5, label="Cosine")
ax.set(title="Make this figure yours", xlabel="Time (s)", ylabel="Amplitude")
ax.grid(True, alpha=0.2)
ax.legend()
'''

# These require Python objects, callbacks, or have effects beyond visual styling.
EXCLUDED = {
    "figure", "axes", "transform", "clip_path", "clip_box", "agg_filter",
    "animated", "picker", "pickradius", "url", "gid", "sketch_params",
    "path_effects", "layout_engine", "canvas", "manager", "mouseover",
    "fontproperties", "prop_cycle", "xticklabels", "yticklabels", "zticklabels",
    "constrained_layout_pads",
}


def plain(value):
    """Convert only losslessly representable, finite JSON values."""
    if isinstance(value, np.ndarray):
        return plain(value.tolist())
    if isinstance(value, np.generic):
        return plain(value.item())
    if value is None or isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, float) and math.isfinite(value):
        return value
    if isinstance(value, (list, tuple)):
        return [plain(item) for item in value]
    if isinstance(value, dict) and all(isinstance(key, str) for key in value):
        return {key: plain(item) for key, item in value.items()}
    raise ValueError("This property requires a Python object")


def resolve(fig, path):
    artist = fig
    for index in path:
        artist = artist.get_children()[index]
    return artist


def properties(artist):
    inspector = ArtistInspector(artist)
    result = []
    for name in sorted(set(inspector.get_setters()) - EXCLUDED):
        getter = getattr(artist, "get_" + name, None)
        if getter is None:
            continue
        try:
            value = plain(getter())
            if len(json.dumps(value)) > 16000:
                continue
            hint = inspector.get_valid_values(name)
        except Exception:
            continue
        result.append({"name": name, "value": value, "hint": hint})
    return result


def demo_figure():
    # Keep this construction identical to the exported standalone script.
    namespace = {}
    exec(DEMO_SOURCE, namespace)
    return namespace["fig"]


class Editor:
    def __init__(self, figure: Figure, *, demo=False):
        self.figure = copy.deepcopy(figure)
        FigureCanvasAgg(self.figure)
        self.figure.canvas.draw()
        self.initial = copy.deepcopy(self.figure)
        self.actions = []
        self.demo = demo
        self.preview = self.render(self.figure)

    @staticmethod
    def render(fig):
        if fig.get_figwidth() <= 0 or fig.get_figheight() <= 0:
            raise ValueError("Figure dimensions must be positive")
        width, height = fig.get_size_inches() * fig.dpi
        if width > 5000 or height > 5000 or width * height > 16_000_000:
            raise ValueError("Preview must be at most 5000 pixels per side and 16 megapixels")
        buffer = io.BytesIO()
        FigureCanvasAgg(fig).print_png(buffer)
        return "data:image/png;base64," + base64.b64encode(buffer.getvalue()).decode()

    def tree(self):
        nodes = []

        def walk(artist, path, depth):
            label = artist.get_label() if hasattr(artist, "get_label") else ""
            if not isinstance(label, str) or label.startswith("_"):
                label = ""
            if hasattr(artist, "get_text"):
                label = artist.get_text() or label
            nodes.append({"path": path, "depth": depth,
                          "name": type(artist).__name__, "label": label[:90]})
            for index, child in enumerate(artist.get_children()):
                walk(child, path + [index], depth + 1)

        walk(self.figure, [], 0)
        return nodes

    def code(self):
        lines = ["# Generated by FigureForge. Apply to the same figure construction.",
                 "def apply_settings(fig):", "    fig.canvas.draw()"]
        for action in self.actions:
            expression = "fig" + "".join(f".get_children()[{i}]" for i in action["path"])
            lines.append(f"    {expression}.set_{action['property']}({action['value']!r})")
            lines.append("    fig.canvas.draw()")
        lines += ["    return fig", ""]
        if self.demo:
            return DEMO_SOURCE + "\n" + "\n".join(lines) + "\napply_settings(fig)\nplt.show()\n"
        return "\n".join(lines) + "\n# Call apply_settings(fig) after your plotting code.\n"

    def state(self, path=None):
        path = [] if path is None else path
        try:
            artist = resolve(self.figure, path)
        except (IndexError, TypeError):
            path, artist = [], self.figure
        return {"tree": self.tree(), "selected": path, "properties": properties(artist),
                "preview": self.preview, "code": self.code(), "edits": len(self.actions)}

    @staticmethod
    def apply(fig, action):
        artist = resolve(fig, action["path"])
        name = action["property"]
        if name not in {prop["name"] for prop in properties(artist)}:
            raise ValueError("Property is not editable")
        value = plain(action["value"])
        getattr(artist, "set_" + name)(value)

    def edit(self, action):
        path = action.get("path")
        if not isinstance(path, list) or not all(type(i) is int and i >= 0 for i in path):
            raise ValueError("Invalid artist path")
        trial = copy.deepcopy(self.figure)
        self.apply(trial, action)
        preview = self.render(trial)  # Invalid setters and render failures never commit.
        self.figure, self.preview = trial, preview
        self.actions.append(copy.deepcopy(action))

    def undo(self, reset=False):
        actions = [] if reset else self.actions[:-1]
        trial = copy.deepcopy(self.initial)
        for action in actions:
            self.apply(trial, action)
            trial.canvas.draw()
        preview = self.render(trial)
        self.figure, self.preview, self.actions = trial, preview, list(actions)
